global com.pameas.brms.model.Message alertMsg;
import com.pameas.brms.model.entity.ClientLocation;
import com.pameas.brms.model.entity.GeofenceNtf;
import com.pameas.brms.model.EmergencyStatus;

rule "test alert message - Scenario 1"
    when
        //emStatus : EmergencyStatus( isEmergency == true);
        gf : GeofenceNtf( gfEvent == "ZONE_IN");
    then
      	alertMsg.setMessage("welcome to geofence :" + gf.getGfName());
end;