global com.pameas.brms.model.Message alertMsg;
import com.pameas.brms.model.entity.ClientLocation;
import com.pameas.brms.model.entity.GeofenceNtf;
import com.pameas.brms.model.EmergencyStatus;
import com.pameas.brms.model.Location;

rule "test alert message - Scenario 1"
    when
        emStatus : EmergencyStatus($loc : emergencyLocation)
        EmergencyStatus( isEmergency == true);
        location : Location( gfName == $loc)
        //gf : GeofenceNtf( gfEvent == "ZONE_IN");
    then
        alertMsg.setAddress("mibu2@sylk.link");
      	alertMsg.setMessage("please exit " + location.getGfName());
end;